### ISSUE TITLE
TaskMessaging

### ISSUE THREAD

**Issue by lgLindstrom** [howroyd/esp32_youtube_series#1]
Hi

I followed your youtube serie on C++ and ESP32. Understandable you did not continue it any further because it must take much of your time.

I am using bits and pieces from it in my projects.
I tried to use your DynamicQueue_t class but run into some trouble.

Is it not missing a constructor?
How do you use it from within another c++ class.

**Comment by howroyd** [comment]
> I followed your youtube serie on C++ and ESP32. Understandable you did not continue it any further because it must take much of your time.

Thank you very much! I am starting a new series but I have just started a new job last week.  When that settles down I will be back to making some videos

> Is it not missing a constructor?

Which one?  The only constructor that makes sense is one that takes the number of items and the size of each item. https://github.com/howroyd/esp32_youtube_series/blob/f3c4d0cfb30929dc9443c36b20c2f7df3ba3e465/application/TaskMessaging/TaskMessaging.h#L231-L234  I did a little bit of  extra work on the `future` branch to also take a queue ID https://github.com/howroyd/esp32_youtube_series/blob/e8cf2ad7dfa1fcf12d57507823c7c448102c3a8a/application/TaskMessaging/TaskMessaging.h#L264-L269

> How do you use it from within another c++ class.

The way it is at the moment, it would need to be passed into the using class.  There is no copy constructor, so unless you add one this is easiest done by passing in b y reference.  Something like this, for example:
```
struct MyThing
{
    MyThing(DynamicQueue_t& queue_ref) : queue{queue}
    {}

    DynamicQueue_t& queue;
};

auto myQueue = DynamicQueue_t{10, sizeof(int)}; // Holds 10 ints
auto mySender = MyThing{myQueue};
auto myReceiver = MyThing{myQueue};
```

**Comment by lgLindstrom** [comment]
What is this used for?
QueueInterface(const QueueInterface& other) :
        queue_len{other.n_items},
        item_size_bytes{other.item_n_bytes},
        h_queue{other.h_queue}
    {}


Den tis 9 aug. 2022 10:55Simon Howroyd ***@***.***> skrev:

**Comment by howroyd** [comment]
That is the copy constructor.  So you can create a copy of the object, which you need to do so you can have two objects referring to the same underlying queue.

That's for the interface base class, I didn't get so far as implementing a copy constructor for the derived classes (DynamicQueue, etc).

https://en.cppreference.com/w/cpp/language/copy_constructor

**Comment by lgLindstrom** [comment]
Hi again

I am using your Queue class and it works splendid when I am running it in a testbed.

I am using your Queue to send and receive data (Topic) from EPS-MQTT  and my testbed abords after maybe 10 minutes. I have the following error in the console logger but it don't give me any clues about what's going on. Neither does internet.

```
I (1136) TEST_MQTT_WRAPPER: Starting TEST_MQTT_WRAPPER
W (1836) wifi:<ba-add>idx:0 (ifx:0, 70:4f:57:1b:d7:83), tid:6, ssn:3, winSize:64
W (2726) wifi:<ba-add>idx:1 (ifx:0, 70:4f:57:1b:d7:83), tid:0, ssn:0, winSize:64
W (5216) TEST_MQTT_WRAPPER: Test data differs 1 591
E (63466) MQTT_CLIENT: mqtt_message_receive: transport_read() error: errno=12
W (63476) MQTT_WRAPPER: MQTT_EVENT_ERROR
E (63476) MQTT_CLIENT: mqtt_process_receive: mqtt_message_receive() returned -1

abort() was called at PC 0x4014fb87 on core 0
```

error=12  say me nothing.


I have started to look int my code to maybe find something wrong. I am using your Queue class with a custom data class like this.

```
class Topic {
    public:
        
        Topic(const char *_name, const char * _data){
            name = new std::string(_name);
            data = new std::string(_data);
    
        };
        ~Topic(){};
        std::string * data{nullptr};
        std::string * name{nullptr};
        
};


```

The idea is that name and data strings are undefined in length before sending and Queue needs a fixed size datatype. This is my way to achieve that.  Only pointers to the strings are stored in the Queue.

Can you see any problems with my approach??   ..... or do you have any idea what  error 12 is. *smile*

**Comment by howroyd** [comment]
ERRNO value 12 is an out of memory error:
https://www.google.com/search?q=errno+12

This is because you have a memory leak in your Topic class.

You call `new` in the constructor, but do not call `delete` to free the memory.

You really shouldn't use `new` and `delete` at all though; they are very easy to make a mistake with:
https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#c149-use-unique_ptr-or-shared_ptr-to-avoid-forgetting-to-delete-objects-created-using-new

As that above link, if you really want something on the free store (heap) then use a smart pointer, as it shows in the link.

HOWEVER, in your case, you are using a `std::string` so there really is no need to have the container on the heap at all.  A `std::string` is two parts, as are many  standard library containers.  There is a part on the stack, containing the length of the string, a pointer to the heap and the allocated size of the pointer to heap.  The second part is similar to a `cstring` on the heap. (this is a simplification, but a good starting point)

When you do `new std::string` you are putting both parts on the heap, which is unnecessary (and slow).

What you probably want is really simple:
```
struct Topic {
    std::string name;
    std::string data;
};
```
_note, the because this is simple aggregation, the compiler will generate all the useful constructors for you, and they will be perfect! Look up "rule of 5"_
_note2, since we want both members `public`, we can just use a `struct` since it faves writing `public`_

Then to use it would be something like this:
```
const auto my_name = "Simon";
const auto my_data = "is awesome";

const auto my_topic = Topic(my_name, my_data);

foo(my_topic);
```

IF, you did want something on the heap for whatever reason, and you want to use `new` and `delete` as per your current Topic, the way would be: (don't recommend this though!)
```
class Topic {
   public:
    Topic(const char* name, const char* data)
        : _name{new std::string(name)}, _data{new std::string(data)} {}
    ~Topic() {
        delete _name;
        delete _data;
    };

    const std::string& name() const { return *_name; }
    const std::string& data() const { return *_data; }

   private:
    std::string* _data{nullptr};
    std::string* _name{nullptr};
};
```

Working demo of this not recommended code with a few (hopefully) helpful comments:
https://godbolt.org/z/nPxGe9shj
_note, I didn't put too much effort into that demo because it's bad practice, but hopefully it is helpful to understand the "why"_

Side note; I assume this is a class containing a message and a topic??  if so, it might be better to use the right words when naming this to save a bit of confusion:
```
struct MqttMessage{
    std::string topic;
    std::string payload;
};
```

**Comment by lgLindstrom** [comment]
Awesome, thanks!
I followed you advice and created a struct instead of class for my data.

No I just need to solve how to get stable data from the esp-idff   mqtt
client.  Never ending problems *smile*










/mvh
/lg
_____________________________________________________
Lars-Göran Lindström
Consius AB
+46 70 190 23 30
***@***.***


Den fre 11 nov. 2022 kl 16:15 skrev Simon Howroyd ***@***.***
